version: '3'

# 网络配置
networks:
  devNetwork:
    driver: ${NETWORKS_DRIVER}

services:
  nsqlookupd:
    build:
      context: ./nsq
    command: /nsqlookupd
    networks:
      - devNetwork
    ports:
      - "${NSQLOOKUP_TCP_PORT}:4160"
      - "${NSQLOOKUP_HTTP_PORT}:4161"

  nsqd:
    build:
      context: ./nsq
    command: /nsqd -broadcast-address=${BROADCAST_ADDR} --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "${NSQD_TCP_PORT}:4150"
      - "${NSQD_HTTP_PORT}:4151"
    networks:
      - devNetwork
  nsqadmin:
    build:
      context: ./nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "${NSQ_ADMIN_PORT}:4171"
    networks:
      - devNetwork