version: '3.5'

# 网络配置
networks:
  devNetwork:
    driver: ${NETWORKS_DRIVER}

# 服务容器配置
services:
  mysql:
    build:
      context: ./mysql
    privileged: true
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}                  # 设置 Mysql 用户名称
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}              # 设置 Mysql 用户密码
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    # 设置 Mysql root 用户密码
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${MySQL_PATH}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"                          # 设置容器3306端口映射指定宿主机端口
    networks:
      - devNetwork
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_MYSQL}
    restart: always

  redis:
    build:
      context: ./redis
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ${REDIS_PATH}:/data                 # 引用 .env 配置中 DATA_PATH_HOST 变量，将宿主机上存放 Redis 数据的目录挂载到容器中 /data 目录
    ports:
      - "${REDIS_PORT}:6379"                          # 设置容器6379端口映射指定宿主机端口
    networks:
      - devNetwork
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_REDIS}
    restart: always

  mongo:
    build:
      context: ./mongo
    restart: always
    privileged: true
    environment:
      - TZ=${TZ}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_PATH}:/data/db
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_MONGO}
    networks:
      - devNetwork

  mongo-express:
    build:
      context: ./mongo_express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}e@mongo:27017/
    networks:
      - devNetwork
    deploy:
      resources:
        limits:
          memory: 1G