version: '3'

services:
  cogpt-api:
    image: geniucker/cogpt:latest
    environment:
      - HOST=0.0.0.0
      - SHARE_TOKEN=${SHARE_TOKEN}
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./db:/app/db
      - ./log:/app/log
    restart: unless-stopped
    container_name: cogpt-api

  web-ui:
    image: yidadaa/chatgpt-next-web
    environment:
      - BASE_URL=${BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CODE=${WEB_UI_CODE}
    ports:
      - ${WEB_PORT}:3000