FROM jenkins/jenkins:latest

LABEL maintainer="FarmerChillax <farmer.notscientific@gmail.com>"

# run jenkins in cli:
# docker pull jenkins/jenkins:latest
# docker run \
#   --name jenkins-docker \
#   --rm \
#   --detach \
#   --privileged \
#   --network jenkins \
#   --network-alias docker \
#   --env DOCKER_TLS_CERTDIR=/certs \
#   --volume jenkins-docker-certs:/certs/client \
#   --volume jenkins-data:/var/jenkins_home \
#   --publish 2376:2376 \
#   docker:dind \
#   --storage-driver overlay2